//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manufacturer
    {
        public manufacturer()
        {
            this.products = new HashSet<product>();
        }
    
        public int MaId { get; set; }
        public string MaName { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
