//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int OrderId { get; set; }
        public int ProId { get; set; }
        public int Amount { get; set; }
        public int DetId { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
